language: node_js
node_js:
  - "12"
branches:
  except:
    - gh-pages
cache:
  directories:
    - "$HOME/.npm"
install:
  - npm ci
script:
  - ng build --prod --base-href=/misconceptions-lab-ui/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: dist/returnOfTheJulian
